"""
Round 2 (GPU): add the generations the second set of experiments needs to an
existing run_full.py run, without regenerating anything already there.

For every applicable (question, condition) record it adds, to augment.jsonl:

  noref        answer from the same evidence with the refusal instruction removed
               -- a truly unconditional Baseline RAG (reviewer: the original baseline
               declined via its prompt, confounding the gate's effect)
  quarantine   (only when a conflict was detected) the evidence with both conflicting
               passages dropped, re-assessed and answered -- so a detected conflict
               routes to "answer from the rest" instead of a blanket refusal
  cr_merged    corrective retrieval that keeps the original evidence: union of original
               and re-retrieved passages, conflicts quarantined, reranked against the
               original question, re-assessed and answered (the pilot's CR replaced the
               evidence wholesale, which made contradictory cases worse at 14B)

records.jsonl is left untouched. Resumable: keys already in augment.jsonl are skipped.

Usage:
  ECERAG_GENERATOR_MODEL=Qwen/Qwen2.5-7B-Instruct python code/augment_records.py results/kaggle/Qwen2.5-7B-Instruct
"""
import argparse
import json
import sys
import time
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))

from ecerag.bootstrap import load_benchmark
from ecerag.generator import MODEL_NAME, generate_answer
from ecerag.reranker import rerank
from ecerag.pipeline import TOP_N_RERANK
from ecerag.sufficiency import quarantine_conflicts
from run_full import assess


def key(rec):
    return f"{rec['qid']}|{rec['condition']}"


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("run_dir")
    ap.add_argument("--limit", type=int, default=None, help="only the first N records (smoke test)")
    args = ap.parse_args()
    run_dir = Path(args.run_dir)
    cfg = json.load(open(run_dir / "run_config.json"))
    if cfg["generator"] != MODEL_NAME:
        sys.exit(f"{run_dir} was generated by {cfg['generator']} but ECERAG_GENERATOR_MODEL is {MODEL_NAME}")
    by_qid = {q["qid"]: q for q in load_benchmark()}
    recs = [json.loads(l) for l in open(run_dir / "records.jsonl", encoding="utf-8")]
    recs = [r for r in recs if r["applicable"]][:args.limit]
    out_path = run_dir / "augment.jsonl"
    done = set()
    if out_path.exists():
        done = {json.loads(l)["key"] for l in open(out_path, encoding="utf-8")}
    print(f"generator={MODEL_NAME}  records={len(recs)}  already done={len(done)}")

    t0 = time.time()
    with open(out_path, "a", encoding="utf-8") as f:
        for i, r in enumerate(recs, start=1):
            if key(r) in done:
                continue
            question = by_qid[r["qid"]]["question"]
            aug = {"key": key(r), "noref": {"answer": generate_answer(question, r["evidence"], allow_refusal=False)}}

            if r["signals"].get("X", 0) >= 1:
                kept = quarantine_conflicts(r["evidence"])
                aug["quarantine"] = assess(question, kept) if kept else None

            pool, seen = [], set()
            for e in r["evidence"] + r["cr"]["evidence"]:
                if e["chunk_id"] not in seen:
                    seen.add(e["chunk_id"])
                    pool.append(e)
            merged = rerank(question, quarantine_conflicts(pool), top_n=TOP_N_RERANK)
            aug["cr_merged"] = assess(question, merged) if merged else None

            f.write(json.dumps(aug, ensure_ascii=False) + "\n")
            f.flush()
            if i % 10 == 0:
                print(f"[{i}/{len(recs)}] elapsed {time.time()-t0:.0f}s", flush=True)
    print(f"Done. Wrote {out_path}")


if __name__ == "__main__":
    main()
